[package]
name = "slackBot"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
slack-morphism = { version = "1.0", features = ["axum", "hyper"] } # <-- The fix is here
axum = "0.7.5"
secrecy = { version = "0.8", features = ["serde"] }
dotenv = "0.15"